apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guest-book-ingress
  namespace: ingress
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guest-book
            port:
              number: 80
